rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: true #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: defaultSecret       #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key
  ignore-url: /user/register,/user/check,/swagger,/v2,/webjars,/seats,/bus,/file

server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: bus-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school_bus?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: root
    password: "0523"
    hikari:
      maximum-pool-size: 20
      max-lifetime: 1800000
      connection-timeout: 30000
      minimum-idle: 5

  redis:
    database: 0
    host: 192.168.127.111
    port: 6379
    password: root
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8


mybatis-plus:
  mapper-locations: classpath*:com/dream/bus/**/mapping/*.xml


logging:
  level.root: info
  level.com.stylefeng: debug
  file:
    path: logs/
    name: bus-user.log
