server:
  port: 8084

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: bus-pay
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school_bus?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: root
    password: "0523"
    hikari:
      maximum-pool-size: 20
      max-lifetime: 1800000
      connection-timeout: 30000
      minimum-idle: 5

  redis:
    database: 0
    host: 192.168.127.111
    port: 6379
    password: root
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8


mybatis-plus:
  mapper-locations: classpath*:com/dream/bus/**/mapping/*.xml


logging:
  level.root: info
  level.com.stylefeng: debug
  file:
    path: logs/
    name: bus-pay.log
mq:
  pay:
    consumer:
      group:
        name: payTopic_cancel_group
    topic: payTopic

rocketmq:
  name-server: 192.168.127.111:9876
  producer:
    group: payProducerGroup
